server:
  port: 8083
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: UTF-8
    # 授权码
    password: JNWHNHGTIGHSNHQW
    # 发送者邮箱地址
    username: xiaowangzlz@163.com
    # 端口（不同邮箱服务器，端口号不同）
    port: 25

  # rabbitmq配置
  rabbitmq:
    username: laowang
    password: Lw20010521
    host: 49.233.53.29
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual

  # redis配置
  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    # 数据库 使用0号数据库
    database: 0
    lettuce:
      pool:
        # 最大连接数  默认为8
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

  # thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
