server:
  port: 8081

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb
    username: root
    password: 111111
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 18000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  # rabbitmq配置
  rabbitmq:
    username: laowang
    password: Lw20010521
    host: 49.233.53.29
    port: 5672
    # 消息确认回调
    publisher-confirm-type: correlated
    # 消息失败回调
    publisher-returns: true


  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    # 数据库 使用0号数据库
    database: 0
    lettuce:
      pool:
        # 最大连接数  默认为8
        max-active: 1024
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

  # 允许循环依赖
  main:
    allow-circular-references: true
  #解决springboot2.6.x整合swagger2报错
  #原因：在springboot2.6.0中将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错，解决办法是切换回原先的AntPathMatcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis-plus配置
mybatis-plus:
  # 配置mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型的别名（默认别名是类名）
  type-aliases-package: com.xiaoping.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

# mybatis SQL 打印 （方法接口所在的包）
logging:
  level:
    com.xiaoping.server.mapper: debug

# JWT的配置参数
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加密使用的密钥
  secret: yeb-secret
  # JWT的有效时间 60*60*24
  expiration: 604800
  # JWT荷载中拿到开头
  tokenHead: Bearer

#OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      # AccessKey
      keyid: LTAI5tSA7L7ZoZ2K4dDuT2yQ
      # AccessSecret
      keysecret: Adfic9Yuy80ZCpmHUGvlsWMANiE79U
      # bucket名称
      bucketname: usual-xiaowang
      # bucket下的文件目录
      filehost: yeb
